### ISSUE TITLE
Getting npm start error 

### ISSUE THREAD

**Issue by moraparamesh** [calendly/buzzwordcrm#5]
getUserInfo = async () => {
                ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buzzwordcrm@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buzzwordcrm@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tcampb** [comment]
Hi @moraparamesh, 

Thanks for creating this issue, it looks like the error occurs when you use a `node` version that is `< 12.0.0`. Could you try upgrading your `node` version to version 12.0 or greater?

**Comment by moraparamesh** [comment]
Thank you @tcampb 
Upgraded to v12.12.0 and its succeeded
